#!/bin/bash
echo "=========================================="
echo "触发 GitHub Actions APK 构建"
echo "=========================================="
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 访问 GitHub Actions:"
echo "   https://github.com/AoNuLL/My-Laptop-Git/actions"
echo ""
echo "2. 点击 'Build Android APK' 工作流"
echo ""
echo "3. 点击 'Run workflow' 按钮"
echo ""
echo "4. 等待 20-30 分钟"
echo ""
echo "5. 在 Artifacts 中下载 APK"
echo ""
echo "=========================================="
echo ""
echo "或者使用 GitHub CLI:"
echo "gh workflow run build-apk.yml"
echo ""
